# Generated by Django 5.2 on 2025-04-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('description', models.TextField()),
                ('estimated_loc', models.IntegerField()),
                ('actual_loc', models.IntegerField()),
                ('estimated_hours', models.IntegerField()),
                ('actual_hours', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.TextField()),
                ('estimated_total_loc', models.IntegerField()),
                ('actual_total_loc', models.IntegerField()),
                ('estimated_total_hours', models.IntegerField()),
                ('actual_total_hours', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('features', models.ManyToManyField(related_name='requirements', to='app.feature')),
            ],
        ),
    ]
